### ISSUE TITLE
Strange crash when changing many files

### ISSUE THREAD

**Issue by stefanpenner** [ember-engines/broccoli-dependency-funnel#25]
during rebase the following is quite common:

```js
Error reporting instrumentation 'build'.
The Broccoli Plugin: [BroccoliDependencyFunnel] failed with:
Error: ENOENT: no such file or directory, unlink '/Users/user/code/the-app/tmp/broccoli_dependency_funnel-output_path-LFLVJztq.tmp/modules/jobs/templates/components/detail/referral-request.js'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1089:18)
    at FSMonitor._measure (/Users/user/code/the-app/node_modules/heimdalljs-fs-monitor/index.js:87:21)
    at Object.unlinkSync (/Users/user/code/the-app/node_modules/heimdalljs-fs-monitor/index.js:108:30)
    at Object.unlink (/Users/user/code/the-app/node_modules/fs-tree-diff/lib/index.js:16:8)
    at applyOperation (/Users/user/code/the-app/node_modules/fs-tree-diff/lib/index.js:222:21)
    at Function.FSTree.applyPatch (/Users/user/code/the-app/node_modules/fs-tree-diff/lib/index.js:210:5)
    at BroccoliDependencyFunnel.build (/Users/user/code/the-app/node_modules/broccoli-dependency-funnel/dist/index.js:152:37)
    at /Users/user/code/the-app/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/Users/user/code/the-app/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/user/code/the-app/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/Users/user/code/the-app/node_modules/rsvp/dist/rsvp.js:522:7)
    at flush (/Users/user/code/the-app/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at BroccoliDependencyFunnel.Plugin (/Users/user/code/the-app/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliDependencyFunnel (/Users/user/code/the-app/node_modules/broccoli-dependency-funnel/dist/index.js:89:90)
    at Class.buildEngineJSTreeWithoutRoutes (/Users/user/code/the-app/node_modules/ember-engines/lib/engine-addon.js:178:10)
    at Class._memoize (/Users/user/code/the-app/node_modules/ember-engines/lib/utils/memoize.js:10:38)
    at Class.treeForPublic (/Users/user/code/the-app/node_modules/ember-engines/lib/engine-addon.js:631:59)
    at Class._treeFor (/Users/user/code/the-app/node_modules/ember-cli/lib/models/addon.js:513:33)
    at Class.treeFor (/Users/user/code/the-app/node_modules/ember-engines/lib/engine-addon.js:847:23)
    at project.addons.map.addon (/Users/user/code/the-app/node_modules/ember-cli/lib/broccoli/ember-app.js:525:20)
    at Array.map (native)
    at EmberApp.addonTreesFor (/Users/user/code/the-app/node_modules/ember-cli/lib/broccoli/ember-app.js:523:30)
    at EmberApp.publicTree (/Users/user/code/the-app/node_modules/ember-cli/lib/broccoli/ember-app.js:791:20)
    at EmberApp.toArray (/Users/user/code/the-app/node_modules/ember-cli/lib/broccoli/ember-app.js:1671:10)
    at EmberApp.toTree (/Users/user/code/the-app/node_modules/ember-cli/lib/broccoli/ember-app.js:1690:30)
    at getAppTree (/Users/user/code/the-app/core/application/ember-cli-build.js:222:14)
    at /Users/user/code/the-app/li-builder/index.js:164:19
    at Array.map (native)
```

**Comment by stefanpenner** [comment]
cc @trentmwillis this occurs apps at work, when switching branches or rebasing.

**Comment by stefanpenner** [comment]
cc @nlfurniss
